### ISSUE TITLE
Doesn't work with this repo

### ISSUE THREAD

**Issue by mahammedzkhan** [dferber90/githubbox#2]
This doesn't seem to be working with this repo:
https://github.com/nature-of-code/noc-book-2

https://githubbox.com/nature-of-code/noc-book-2

**Comment by dferber90** [comment]
I’m on my phone at tj

**Comment by dferber90** [comment]
Update: I checked. It's not related to githubbox.

Thanks for reporting anyhow! I'm aware that the line between githubbox and CodeSandbox is a bit blurry :)
