### ISSUE TITLE
Open codesandbox from one specific file

### ISSUE THREAD

**Issue by dillonreedy** [dferber90/githubbox#6]
If the github url navigates to one specific file within the repo, it'd be nice to have some kind of option to specify in the url parameters on whether you'd like a codesandbox opened on the specific file or the entire repo.

**Comment by dferber90** [comment]
At the moment the following will happen

`https://github.com/dferber90/githubbox/blob/master/src/location.js` sends you to
`https://codesandbox.io/s/github/dferber90/githubbox/tree/master?file=/src/location.js`

If I understand correctly, you'd like to be able to add a query param or something similar before replacing `github.com` with `githubbox.com`.

Is there a reason not to use the GitHub UI to navigate to the file/root before replacing `github.com` with `githubbox.com`?

I haven't come across this use case and I think it would be really hard to discover as a feature, so I'm not sure it' worth the additional complexity.

**Comment by dillonreedy** [comment]
I was thinking to add the url parameter so as to give other users the choice on whether or not they'd use it.

But yeah, you essentially have the idea.

We have a [repo](https://github.com/recharts/recharts) containing a "demo" folder. This demo folder contains a .js file for each example, and it'd be nice to be able create a githubbox url for each example.

So for example we'd want:
https://githubbox.com/recharts/recharts/blob/master/demo/component/AreaChart.js

To open a codesandbox of AreaChart.js with its dependencies.

This can be with or without the url parameter.

**Comment by dferber90** [comment]
Ah, I think it's not possible to run a specific file CodeSandbox-wise. `githubbox.com` rewrites the `github.com` urls to `codesandbox.io/s/github` so we're limited to what the importer under [`codesandbox.io/s/github`](https://codesandbox.io/s/github/) offers.

It supports influencing which subdirectory serve as the root, but not booting from a specific file which is what you'd want afaik. From the CodeSandbox docs:

> Import from GitHub
>
> You can import a GitHub repository in to CodeSandbox using our import wizard and pasting the URL to your GitHub repository. **We support custom branches and subdirectories.**

https://codesandbox.io/docs/importing#import-from-github

Seems like you'd need to restructure the demos to have a separate folder and one `package.json` at the root of each demo folder, but I might be wrong. I haven't used the subdirectories extensively. Hope this helps

**Comment by dillonreedy** [comment]
Ah gotcha, all good.
