### ISSUE TITLE
We could not find the sandbox you're looking for.

### ISSUE THREAD

**Issue by miquelvir** [dferber90/githubbox#9]
I have tried opening githubbox.com/miquelvir/centrifuga4 but I get the error "We could not find the sandbox you're looking for.".

Githubbox url: githubbox.com/miquelvir/centrifuga4
Github url: github.com/miquelvir/centrifuga4

**Comment by dferber90** [comment]
This seems to be an issue with CodeSandbox itself, or with your repository. Maybe there's an unsupported file in there.

For example, if you use the CodeSandbox importer directly by visiting https://codesandbox.io/s/github and pasting in https://github.com/miquelvir/centrifuga4 it fails as well.

It doesn't seem like an issue with githubbox. I don't work for CodeSandbox, so I can only point you forward unfortunately. Could you try opening an issue with CodeSandbox directly? This seems to be the right place: https://github.com/codesandbox/codesandbox-importers

I'll close this issue, as there's nothing I can in githubbox to resolve it. Hope you get it working!
